### ISSUE TITLE
When getting access token TypeError: 'NoneType' object has no attribute '__getitem__

### ISSUE THREAD

**Issue by hassanshaikley** [Flibber/Flibber#16]
Getting this on my first run in the getAccessToken() method.

Traceback (most recent call last):
  File "flibber.py", line 700, in <module>
    begin()
  File "flibber.py", line 686, in begin
    getAccessToken()
  File "flibber.py", line 264, in getAccessToken
    options.ACCESS_TOKEN = str(data["access_token"])
TypeError: 'NoneType' object has no attribute '**getitem**

So basically data is empty.

data = reqURL(tokenURL, post, "POST")

And I am not sure why. My variables are set properly.

**Comment by hassanshaikley** [comment]
Oh I forgot to add my IP address! Didn't see that.
I might add to the Readme. Don't mind me if I do. ; )
