### ISSUE TITLE
A user following less than half of their follower count causes script to end

### ISSUE THREAD

**Issue by treblig** [Flibber/Flibber#5]
```
[CODE] 200
[GREL] You are following user 29935102
[NUM#] Request #55
[RATE] Remaining API calls: 4888/5000
[RURL] https://api.instagram.com/v1/users/463615831
[FLDS] access_token=1751088727.5b8dd67.bc2a4bcdf5dc4259a2dc3495f54b05dc&client_id=5b8dd679023b4c5792c8bb3223264249
[HTTP] GET
[CODE] 200
[FLLW] User 463615831 is following less than half of their follower count. Skipping...

[STAT] Statistics from run:
[STAT] Total Unfollows: 0
[STAT] Total Follows: 1
[STAT] Total Likes: 1
[STAT] Total API Calls: 55

Traceback (most recent call last):
  File "flibber.py", line 663, in <module>
    begin()
  File "flibber.py", line 655, in begin
    decider()
  File "flibber.py", line 637, in decider
    likeUsers(MAX_COUNT, 0, tag, 0, 0)
  File "flibber.py", line 506, in likeUsers
    likeCount = likeCount + int(likeAndFollowUser(userID))
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by ChipWolf** [comment]
Fixed in latest version
