### ISSUE TITLE
int() argument must be a string or a number, not 'NoneType' when user follows less than their follower count

### ISSUE THREAD

**Issue by treblig** [Flibber/Flibber#7]
```
[CODE] 200
[NUM#] Request #154
[RATE] Remaining API calls: 4158/5000
[RURL] https://api.instagram.com/v1/users/self/media/liked
[FLDS]  [REDACTED]
[HTTP] GET
[CODE] 200
[LIKE] 298 pictures added to interaction blacklist
[NUM#] Request #155
[RATE] Remaining API calls: 4157/5000
[RURL] https://api.instagram.com/v1/tags/exploremore/media/recent
[FLDS]  [REDACTED]
[HTTP] GET
[CODE] 200
[NUM#] Request #156
[RATE] Remaining API calls: 4156/5000
[RURL] https://api.instagram.com/v1/users/354705062
[FLDS] [REDACTED]
[HTTP] GET
[CODE] 200
[FLLW] User 354705062 is following less than half of their follower count. Skipping...

[EXEP] int() argument must be a string or a number, not 'NoneType'

[STAT] Statistics from run:
[STAT] Total Unfollows: 0
[STAT] Total Follows: 0
[STAT] Total Likes: 0
[STAT] Total API Calls: 156
```

**Comment by treblig** [comment]
More detailed traceback:

```
Traceback (most recent call last):
  File "flibber.py", line 663, in <module>
    begin()
  File "flibber.py", line 655, in begin
    decider()
  File "flibber.py", line 637, in decider
    likeUsers(MAX_COUNT, 0, tag, 0, 0)
  File "flibber.py", line 506, in likeUsers
    likeCount = likeCount + int(likeAndFollowUser(userID))
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by ChipWolf** [comment]
That's an old version. Get the new one.
